
---
title: "Diabetes data - Check Box"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    logo: logo.png
    source_code: embed
    social: menu

runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(flexdashboard)
library(tidyverse)
library(plotly)
library(knitr)
library(DT)
df <- read_csv('diabetes.csv')
df$preg <- case_when(df$Pregnancies >= 1 ~ "Has been Pregnant",df$Pregnancies>=4~"Above Average Pregnancies",TRUE ~"Never been pregnant")
df$Outcome = factor(df$Outcome)

preg<- unique(df$preg)
```

{.sidebar}
=======================================================================
 

```{r}
checkboxGroupInput(inputId = "pregnancy_input", 
                   label = h3("Select pregnancy status"),
                   choices = preg, 
                   inline = TRUE,
                   selected = 'Has been Pregnant')


```

Main Tab 1
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Density Plot

```{r}
renderPlotly({
  p1 <- df %>% 
    filter(preg==input$pregnancy_input) %>% 
    ggplot(aes(x=BMI, color=preg))+
    geom_density()
  ggplotly(p1)
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### Bar Plot

```{r}
renderPlotly({
  p2 <- df %>% 
    filter(preg==input$pregnancy_input) %>% 
    ggplot(aes(x=BMI, y = Insulin,fill=preg))+
    geom_col()
  ggplotly(p2)
})
```
